#!/bin/bash

# Script for testing

#set -e

ext=""
chk=""
mkg=""

# Argument parsing
while (( $# )); do
	case $1 in
	--)
		shift
		break
	;;
	-x|--make-extras) EXT="--make-extras"; echo "Making extra files (reports, symbol files etc)." ;;
	-c|--check-disassembly) CHK="--check-disassembly"; echo "Checking disassemblies against known good." ;;
	-m|--make-known-good) MKG="--make-known-good"; echo "Making known good." ;;
	-*)
		echo >&2 "Invalid option: $1"
		exit 1
	;;
	esac
	shift
done

OPT="$EXT $CHK $MKG"

echo "Options: $OPT"

python3 go.py "example8080"     $OPT --assemblers z88dk-8080
python3 go.py "test8080"        $OPT --assemblers z88dk-8080

python3 go.py "string_stuff1"   $OPT --assemblers acme beebasm
python3 go.py "string_stuff2"   $OPT --assemblers beebasm
python3 go.py "moving1"         $OPT --assemblers acme beebasm xa
python3 go.py "moving2"         $OPT --assemblers acme beebasm xa
python3 go.py "moving3"         $OPT --assemblers acme beebasm xa
python3 go.py "helloworld"      $OPT --assemblers acme beebasm xa
python3 go.py "local_labels"    $OPT --assemblers acme beebasm xa
python3 go.py "basic4"          $OPT --assemblers acme beebasm xa
python3 go.py "dfs226"          $OPT --assemblers acme beebasm xa
python3 go.py "dfs226b"         $OPT --assemblers acme beebasm xa
python3 go.py "anfs418"         $OPT --assemblers acme beebasm xa
python3 go.py "move"            $OPT --assemblers acme beebasm xa
python3 go.py "move2"           $OPT --assemblers acme beebasm xa
python3 go.py "split"           $OPT --assemblers acme beebasm xa
python3 go.py "chuckie"         $OPT --assemblers acme beebasm xa
python3 go.py "subroutine_test" $OPT --assemblers acme beebasm xa
python3 go.py "acorn_os_calls"  $OPT --assemblers acme beebasm xa

