; Memory locations

    org &2000

.pydis_start
    lda #0                                                            ; 2000: a9 00       ..
    lda #1                                                            ; 2002: a9 01       ..
    lda #2                                                            ; 2004: a9 02       ..
    lda #3                                                            ; 2006: a9 03       ..
    lda #4                                                            ; 2008: a9 04       ..
    lda #5                                                            ; 200a: a9 05       ..
    lda #6                                                            ; 200c: a9 06       ..
    lda #7                                                            ; 200e: a9 07       ..
    lda #8                                                            ; 2010: a9 08       ..
    lda #9                                                            ; 2012: a9 09       ..
    lda #&0a                                                          ; 2014: a9 0a       ..
    lda #&0b                                                          ; 2016: a9 0b       ..
    lda #&0c                                                          ; 2018: a9 0c       ..
    lda #&0d                                                          ; 201a: a9 0d       ..
    lda #&0e                                                          ; 201c: a9 0e       ..
    lda #&0f                                                          ; 201e: a9 0f       ..
    lda #&10                                                          ; 2020: a9 10       ..
    lda #&11                                                          ; 2022: a9 11       ..
    lda #&12                                                          ; 2024: a9 12       ..
    lda #&13                                                          ; 2026: a9 13       ..
    lda #&14                                                          ; 2028: a9 14       ..
    lda #&15                                                          ; 202a: a9 15       ..
    lda #&16                                                          ; 202c: a9 16       ..
    lda #&17                                                          ; 202e: a9 17       ..
    lda #&18                                                          ; 2030: a9 18       ..
    lda #&19                                                          ; 2032: a9 19       ..
    lda #&1a                                                          ; 2034: a9 1a       ..
    lda #&1b                                                          ; 2036: a9 1b       ..
    lda #&1c                                                          ; 2038: a9 1c       ..
    lda #&1d                                                          ; 203a: a9 1d       ..
    lda #&1e                                                          ; 203c: a9 1e       ..
    lda #&1f                                                          ; 203e: a9 1f       ..
    lda #' '                                                          ; 2040: a9 20       .
    lda #'!'                                                          ; 2042: a9 21       .!
    lda #&22                                                          ; 2044: a9 22       ."
    lda #'#'                                                          ; 2046: a9 23       .#
    lda #'$'                                                          ; 2048: a9 24       .$
    lda #'%'                                                          ; 204a: a9 25       .%
    lda #'&'                                                          ; 204c: a9 26       .&
    lda #'''                                                          ; 204e: a9 27       .'
    lda #'('                                                          ; 2050: a9 28       .(
    lda #')'                                                          ; 2052: a9 29       .)
    lda #'*'                                                          ; 2054: a9 2a       .*
    lda #'+'                                                          ; 2056: a9 2b       .+
    lda #','                                                          ; 2058: a9 2c       .,
    lda #'-'                                                          ; 205a: a9 2d       .-
    lda #'.'                                                          ; 205c: a9 2e       ..
    lda #'/'                                                          ; 205e: a9 2f       ./
    lda #'0'                                                          ; 2060: a9 30       .0
    lda #'1'                                                          ; 2062: a9 31       .1
    lda #'2'                                                          ; 2064: a9 32       .2
    lda #'3'                                                          ; 2066: a9 33       .3
    lda #'4'                                                          ; 2068: a9 34       .4
    lda #'5'                                                          ; 206a: a9 35       .5
    lda #'6'                                                          ; 206c: a9 36       .6
    lda #'7'                                                          ; 206e: a9 37       .7
    lda #'8'                                                          ; 2070: a9 38       .8
    lda #'9'                                                          ; 2072: a9 39       .9
    lda #':'                                                          ; 2074: a9 3a       .:
    lda #';'                                                          ; 2076: a9 3b       .;
    lda #'<'                                                          ; 2078: a9 3c       .<
    lda #'='                                                          ; 207a: a9 3d       .=
    lda #'>'                                                          ; 207c: a9 3e       .>
    lda #'?'                                                          ; 207e: a9 3f       .?
    lda #'@'                                                          ; 2080: a9 40       .@
    lda #'A'                                                          ; 2082: a9 41       .A
    lda #'B'                                                          ; 2084: a9 42       .B
    lda #'C'                                                          ; 2086: a9 43       .C
    lda #'D'                                                          ; 2088: a9 44       .D
    lda #'E'                                                          ; 208a: a9 45       .E
    lda #'F'                                                          ; 208c: a9 46       .F
    lda #'G'                                                          ; 208e: a9 47       .G
    lda #'H'                                                          ; 2090: a9 48       .H
    lda #'I'                                                          ; 2092: a9 49       .I
    lda #'J'                                                          ; 2094: a9 4a       .J
    lda #'K'                                                          ; 2096: a9 4b       .K
    lda #'L'                                                          ; 2098: a9 4c       .L
    lda #'M'                                                          ; 209a: a9 4d       .M
    lda #'N'                                                          ; 209c: a9 4e       .N
    lda #'O'                                                          ; 209e: a9 4f       .O
    lda #'P'                                                          ; 20a0: a9 50       .P
    lda #'Q'                                                          ; 20a2: a9 51       .Q
    lda #'R'                                                          ; 20a4: a9 52       .R
    lda #'S'                                                          ; 20a6: a9 53       .S
    lda #'T'                                                          ; 20a8: a9 54       .T
    lda #'U'                                                          ; 20aa: a9 55       .U
    lda #'V'                                                          ; 20ac: a9 56       .V
    lda #'W'                                                          ; 20ae: a9 57       .W
    lda #'X'                                                          ; 20b0: a9 58       .X
    lda #'Y'                                                          ; 20b2: a9 59       .Y
    lda #'Z'                                                          ; 20b4: a9 5a       .Z
    lda #'['                                                          ; 20b6: a9 5b       .[
    lda #'\'                                                          ; 20b8: a9 5c       .\
    lda #']'                                                          ; 20ba: a9 5d       .]
    lda #'^'                                                          ; 20bc: a9 5e       .^
    lda #'_'                                                          ; 20be: a9 5f       ._
    lda #'`'                                                          ; 20c0: a9 60       .`
    lda #'a'                                                          ; 20c2: a9 61       .a
    lda #'b'                                                          ; 20c4: a9 62       .b
    lda #'c'                                                          ; 20c6: a9 63       .c
    lda #'d'                                                          ; 20c8: a9 64       .d
    lda #'e'                                                          ; 20ca: a9 65       .e
    lda #'f'                                                          ; 20cc: a9 66       .f
    lda #'g'                                                          ; 20ce: a9 67       .g
    lda #'h'                                                          ; 20d0: a9 68       .h
    lda #'i'                                                          ; 20d2: a9 69       .i
    lda #'j'                                                          ; 20d4: a9 6a       .j
    lda #'k'                                                          ; 20d6: a9 6b       .k
    lda #'l'                                                          ; 20d8: a9 6c       .l
    lda #'m'                                                          ; 20da: a9 6d       .m
    lda #'n'                                                          ; 20dc: a9 6e       .n
    lda #'o'                                                          ; 20de: a9 6f       .o
    lda #'p'                                                          ; 20e0: a9 70       .p
    lda #'q'                                                          ; 20e2: a9 71       .q
    lda #'r'                                                          ; 20e4: a9 72       .r
    lda #'s'                                                          ; 20e6: a9 73       .s
    lda #'t'                                                          ; 20e8: a9 74       .t
    lda #'u'                                                          ; 20ea: a9 75       .u
    lda #'v'                                                          ; 20ec: a9 76       .v
    lda #'w'                                                          ; 20ee: a9 77       .w
    lda #'x'                                                          ; 20f0: a9 78       .x
    lda #'y'                                                          ; 20f2: a9 79       .y
    lda #'z'                                                          ; 20f4: a9 7a       .z
    lda #'{'                                                          ; 20f6: a9 7b       .{
    lda #'|'                                                          ; 20f8: a9 7c       .|
    lda #'}'                                                          ; 20fa: a9 7d       .}
    lda #'~'                                                          ; 20fc: a9 7e       .~
    lda #&7f                                                          ; 20fe: a9 7f       ..
    lda #&80                                                          ; 2100: a9 80       ..
    lda #&81                                                          ; 2102: a9 81       ..
    lda #&82                                                          ; 2104: a9 82       ..
    lda #&83                                                          ; 2106: a9 83       ..
    lda #&84                                                          ; 2108: a9 84       ..
    lda #&85                                                          ; 210a: a9 85       ..
    lda #&86                                                          ; 210c: a9 86       ..
    lda #&87                                                          ; 210e: a9 87       ..
    lda #&88                                                          ; 2110: a9 88       ..
    lda #&89                                                          ; 2112: a9 89       ..
    lda #&8a                                                          ; 2114: a9 8a       ..
    lda #&8b                                                          ; 2116: a9 8b       ..
    lda #&8c                                                          ; 2118: a9 8c       ..
    lda #&8d                                                          ; 211a: a9 8d       ..
    lda #&8e                                                          ; 211c: a9 8e       ..
    lda #&8f                                                          ; 211e: a9 8f       ..
    lda #&90                                                          ; 2120: a9 90       ..
    lda #&91                                                          ; 2122: a9 91       ..
    lda #&92                                                          ; 2124: a9 92       ..
    lda #&93                                                          ; 2126: a9 93       ..
    lda #&94                                                          ; 2128: a9 94       ..
    lda #&95                                                          ; 212a: a9 95       ..
    lda #&96                                                          ; 212c: a9 96       ..
    lda #&97                                                          ; 212e: a9 97       ..
    lda #&98                                                          ; 2130: a9 98       ..
    lda #&99                                                          ; 2132: a9 99       ..
    lda #&9a                                                          ; 2134: a9 9a       ..
    lda #&9b                                                          ; 2136: a9 9b       ..
    lda #&9c                                                          ; 2138: a9 9c       ..
    lda #&9d                                                          ; 213a: a9 9d       ..
    lda #&9e                                                          ; 213c: a9 9e       ..
    lda #&9f                                                          ; 213e: a9 9f       ..
    lda #&a0                                                          ; 2140: a9 a0       ..
    lda #&a1                                                          ; 2142: a9 a1       ..
    lda #&a2                                                          ; 2144: a9 a2       ..
    lda #&a3                                                          ; 2146: a9 a3       ..
    lda #&a4                                                          ; 2148: a9 a4       ..
    lda #&a5                                                          ; 214a: a9 a5       ..
    lda #&a6                                                          ; 214c: a9 a6       ..
    lda #&a7                                                          ; 214e: a9 a7       ..
    lda #&a8                                                          ; 2150: a9 a8       ..
    lda #&a9                                                          ; 2152: a9 a9       ..
    lda #&aa                                                          ; 2154: a9 aa       ..
    lda #&ab                                                          ; 2156: a9 ab       ..
    lda #&ac                                                          ; 2158: a9 ac       ..
    lda #&ad                                                          ; 215a: a9 ad       ..
    lda #&ae                                                          ; 215c: a9 ae       ..
    lda #&af                                                          ; 215e: a9 af       ..
    lda #&b0                                                          ; 2160: a9 b0       ..
    lda #&b1                                                          ; 2162: a9 b1       ..
    lda #&b2                                                          ; 2164: a9 b2       ..
    lda #&b3                                                          ; 2166: a9 b3       ..
    lda #&b4                                                          ; 2168: a9 b4       ..
    lda #&b5                                                          ; 216a: a9 b5       ..
    lda #&b6                                                          ; 216c: a9 b6       ..
    lda #&b7                                                          ; 216e: a9 b7       ..
    lda #&b8                                                          ; 2170: a9 b8       ..
    lda #&b9                                                          ; 2172: a9 b9       ..
    lda #&ba                                                          ; 2174: a9 ba       ..
    lda #&bb                                                          ; 2176: a9 bb       ..
    lda #&bc                                                          ; 2178: a9 bc       ..
    lda #&bd                                                          ; 217a: a9 bd       ..
    lda #&be                                                          ; 217c: a9 be       ..
    lda #&bf                                                          ; 217e: a9 bf       ..
    lda #&c0                                                          ; 2180: a9 c0       ..
    lda #&c1                                                          ; 2182: a9 c1       ..
    lda #&c2                                                          ; 2184: a9 c2       ..
    lda #&c3                                                          ; 2186: a9 c3       ..
    lda #&c4                                                          ; 2188: a9 c4       ..
    lda #&c5                                                          ; 218a: a9 c5       ..
    lda #&c6                                                          ; 218c: a9 c6       ..
    lda #&c7                                                          ; 218e: a9 c7       ..
    lda #&c8                                                          ; 2190: a9 c8       ..
    lda #&c9                                                          ; 2192: a9 c9       ..
    lda #&ca                                                          ; 2194: a9 ca       ..
    lda #&cb                                                          ; 2196: a9 cb       ..
    lda #&cc                                                          ; 2198: a9 cc       ..
    lda #&cd                                                          ; 219a: a9 cd       ..
    lda #&ce                                                          ; 219c: a9 ce       ..
    lda #&cf                                                          ; 219e: a9 cf       ..
    lda #&d0                                                          ; 21a0: a9 d0       ..
    lda #&d1                                                          ; 21a2: a9 d1       ..
    lda #&d2                                                          ; 21a4: a9 d2       ..
    lda #&d3                                                          ; 21a6: a9 d3       ..
    lda #&d4                                                          ; 21a8: a9 d4       ..
    lda #&d5                                                          ; 21aa: a9 d5       ..
    lda #&d6                                                          ; 21ac: a9 d6       ..
    lda #&d7                                                          ; 21ae: a9 d7       ..
    lda #&d8                                                          ; 21b0: a9 d8       ..
    lda #&d9                                                          ; 21b2: a9 d9       ..
    lda #&da                                                          ; 21b4: a9 da       ..
    lda #&db                                                          ; 21b6: a9 db       ..
    lda #&dc                                                          ; 21b8: a9 dc       ..
    lda #&dd                                                          ; 21ba: a9 dd       ..
    lda #&de                                                          ; 21bc: a9 de       ..
    lda #&df                                                          ; 21be: a9 df       ..
    lda #&e0                                                          ; 21c0: a9 e0       ..
    lda #&e1                                                          ; 21c2: a9 e1       ..
    lda #&e2                                                          ; 21c4: a9 e2       ..
    lda #&e3                                                          ; 21c6: a9 e3       ..
    lda #&e4                                                          ; 21c8: a9 e4       ..
    lda #&e5                                                          ; 21ca: a9 e5       ..
    lda #&e6                                                          ; 21cc: a9 e6       ..
    lda #&e7                                                          ; 21ce: a9 e7       ..
    lda #&e8                                                          ; 21d0: a9 e8       ..
    lda #&e9                                                          ; 21d2: a9 e9       ..
    lda #&ea                                                          ; 21d4: a9 ea       ..
    lda #&eb                                                          ; 21d6: a9 eb       ..
    lda #&ec                                                          ; 21d8: a9 ec       ..
    lda #&ed                                                          ; 21da: a9 ed       ..
    lda #&ee                                                          ; 21dc: a9 ee       ..
    lda #&ef                                                          ; 21de: a9 ef       ..
    lda #&f0                                                          ; 21e0: a9 f0       ..
    lda #&f1                                                          ; 21e2: a9 f1       ..
    lda #&f2                                                          ; 21e4: a9 f2       ..
    lda #&f3                                                          ; 21e6: a9 f3       ..
    lda #&f4                                                          ; 21e8: a9 f4       ..
    lda #&f5                                                          ; 21ea: a9 f5       ..
    lda #&f6                                                          ; 21ec: a9 f6       ..
    lda #&f7                                                          ; 21ee: a9 f7       ..
    lda #&f8                                                          ; 21f0: a9 f8       ..
    lda #&f9                                                          ; 21f2: a9 f9       ..
    lda #&fa                                                          ; 21f4: a9 fa       ..
    lda #&fb                                                          ; 21f6: a9 fb       ..
    lda #&fc                                                          ; 21f8: a9 fc       ..
    lda #&fd                                                          ; 21fa: a9 fd       ..
    lda #&fe                                                          ; 21fc: a9 fe       ..
    lda #&ff                                                          ; 21fe: a9 ff       ..
    rts                                                               ; 2200: 60          `

.pydis_end

save pydis_start, pydis_end
